apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "autocompounder.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.appConfig.env }}
  {{ $key | quote }}: {{ $value | quote }}
{{- end }}